-- MySQL Script generated by MySQL Workbench
-- 05/10/15 16:32:59
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Osoba` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `JMBG` VARCHAR(45) NOT NULL,
  `Adresa` VARCHAR(45) NOT NULL,
  `Telefon` VARCHAR(45) NOT NULL,
  `DatumZaposljenja` DATE NOT NULL,
  `Pozicija` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `id_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `JMBG_UNIQUE` (`JMBG` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Firma` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zaposlenik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zaposlenik` (
  `Osoba_ID` INT NOT NULL,
  `Firma_ID` INT NOT NULL,
  `Osnovica` DOUBLE NOT NULL,
  `Satnica` DOUBLE NOT NULL,
  `StvarniRad` INT NOT NULL,
  `BrojRadnihDana` INT NOT NULL,
  `Bolovanje` INT NOT NULL,
  `DnevniTopliObrok` DOUBLE NOT NULL,
  `GodineStaza` INT NOT NULL,
  `GodisnjiOdmor` INT NOT NULL,
  PRIMARY KEY (`Osoba_ID`, `Firma_ID`),
  INDEX `fk_Zaposlenik_Firma1_idx` (`Firma_ID` ASC),
  CONSTRAINT `fk_Zaposlenik_Osoba`
    FOREIGN KEY (`Osoba_ID`)
    REFERENCES `mydb`.`Osoba` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zaposlenik_Firma1`
    FOREIGN KEY (`Firma_ID`)
    REFERENCES `mydb`.`Firma` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operater`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operater` (
  `Osoba_ID` INT NOT NULL,
  `Firma_ID` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Privilegije` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  PRIMARY KEY (`Osoba_ID`, `Firma_ID`),
  INDEX `fk_Operater_Firma1_idx` (`Firma_ID` ASC),
  CONSTRAINT `fk_Operater_Osoba1`
    FOREIGN KEY (`Osoba_ID`)
    REFERENCES `mydb`.`Osoba` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operater_Firma1`
    FOREIGN KEY (`Firma_ID`)
    REFERENCES `mydb`.`Firma` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `Osoba_ID` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  PRIMARY KEY (`Osoba_ID`),
  CONSTRAINT `fk_Admin_Osoba1`
    FOREIGN KEY (`Osoba_ID`)
    REFERENCES `mydb`.`Osoba` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
